apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: test-nfs-app
    run: svc-test
  name: svc-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: test-nfs-app
    run: test-pod
status:
  loadBalancer: {}
